### ISSUE TITLE
Subdomain URL not found

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#21] opened 2018-09-17 17:55 UTC
I checked out the prior issues forum on this topic, but since it is closed, I am going to post my issue here. I went through the instructions, and my main domain works. The subdomain says the URL is not found. I checked out the digital ocean ssh to make sure that I had cloned my P1 root correctly, and it is located there. Are there any other suggestions on where to double check for issues? The subdomain is p1.christianpowell.me.

**Comment by mdeforest** [comment] 2018-09-17 17:59
What did you use to create your domain?  Did you add the CNAME record to the DNS configuration? Instructions for doing that on Namecheap were provided here: https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/production-domain.md

**Comment by mdeforest** [comment] 2018-09-17 18:06
It can also take some time for the domain to propagate to registrar's DNS. How long ago did you set it up?

**Comment by pausman** [comment] 2018-09-17 18:06
I can ping p1.christianpowell.me so I dont think it is the cname record.  

I think it is the definition of the virtual directory in /etc/apache2/sites-enabled/000-default.conf on the production server.  

If you already checked this then I would make sure you have restarted the web server : 
$ service apache2 restart

If still stuck then I would post your 000-default.conf file.

**Comment by cpowell1** [comment] 2018-09-17 22:59
It has been over two hours, and so I redid the process. I am still getting the same error, so I will post the following code to maybe see where I went wrong. 
```Last login: Mon Sep 17 17:53:15 on console
You have new mail.
CPOWELL ~
$ ssh root@104.248.48.252
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-34-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Sep 17 22:57:17 UTC 2018

  System load:  0.0               Processes:           95
  Usage of /:   6.9% of 24.06GB   Users logged in:     0
  Memory usage: 31%               IP address for eth0: 104.248.48.252
  Swap usage:   0%

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


********************************************************************************

Welcome to DigitalOcean's One-Click LAMP Droplet. 
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The LAMP One-Click Quickstart guide: http://do.co/lamp1804#start
 * Your LAMP website: http://104.248.48.252

On the server:
 * The default web root is located at /var/www/html
 * The MySQL root password is saved in /root/.digitalocean_password
 * Certbot is preinstalled. Run it to configure HTTPS. See
   http://do.co/lamp1804#enable-https for more detail.

For help and more information, visit http://do.co/lamp1804

********************************************************************************
To delete this message of the day: rm -rf /etc/update-motd.d/99-one-click
Last login: Mon Sep 17 17:46:17 2018 from 108.212.196.205
root@dwa:~# nano /etc/apache2/sites-enabled/000-default.conf

  GNU nano 2.9.3     /etc/apache2/sites-enabled/000-default.conf                

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml $
        </IfModule>

</VirtualHost>

<VirtualHost *:80>
  ServerName p1.christianpowell.me
  DocumentRoot "/var/www/html/p1”
  <Directory "/var/www/html/p1”>
    AllowOverride All
  </Directory>
</VirtualHost>
```

**Comment by pausman** [comment] 2018-09-17 23:03
what is the name of your php file? index.php?

**Comment by cpowell1** [comment] 2018-09-17 23:12
Yes.. and the christianpowell.me works and goes to the Digital Ocean page.

**Comment by pausman** [comment] 2018-09-17 23:15
So if you log onto the production server and cd to /var/www/html and do a dir (ls) you see the p1 directory?

**Comment by cpowell1** [comment] 2018-09-17 23:20
Yes! There is an index.html and a p1 which is what has the index.php in it

**Comment by susanBuck** [comment] 2018-09-17 23:29
@cpowell1 I think I spotted a problem in your VirtualHost block - note how the closing quote for DocumentRoot and Directory are "curly quotes" ([ref](http://smartquotesforsmartpeople.com/)), but it should be straight quotes.

```
DocumentRoot "/var/www/html/p1”
<Directory "/var/www/html/p1”>
```

Should be:
```
DocumentRoot "/var/www/html/p1"
<Directory "/var/www/html/p1">
```

Try making that change and restarting Apache again.

**Comment by cpowell1** [comment] 2018-09-17 23:35
That did the trick. Thank you all for the time and effort!

**Comment by susanBuck** [comment] 2018-09-17 23:41
Glad that did the trick.

Sometimes when copying/pasting into a text editor, especially if it's in rich-text mode, it'll transform straight quotes to curly quotes. 

That can be helpful for general writing, but it's problematic with code.

In the notes, I did suggest copying the VirtualHost block into a text editor in order to easily edit it, so I suspect that might be the root cause.

**Closed** 2018-09-20 00:43 UTC
